import type { Property } from "@/components/PropertyCard";

const BASE = process.env.NEXT_PUBLIC_BASE_PATH || "";
const C7 = `${BASE}/Usadba/cottages/cottage%207`;
const C10 = `${BASE}/Usadba/cottages/cottage%2010`;
const C5 = `${BASE}/Usadba/cottages/cottage%205`;
const C3 = `${BASE}/Usadba/cottages/cottage%203`;
const C1B = `${BASE}/Usadba/cottages/cottage%201-B`;
const C2 = `${BASE}/Usadba/cottages/cottage%202`;
const A7 = `${BASE}/Usadba/apartments/apartments%207`;
const A4 = `${BASE}/Usadba/apartments/apartments%204`;
const A52 = `${BASE}/Usadba/apartments/apartments%205-2`;
const A51 = `${BASE}/Usadba/apartments/apartments%205-1`;
const A2 = `${BASE}/Usadba/apartments/apartments%202`;
const A3 = `${BASE}/Usadba/apartments/apartments%203`;

export const cottages: Property[] = [
  {
    id: "cottage-eco7",
    slug: "eco-kottedzh-7",
    title: "Деревянный эко коттедж №7",
    type: "cottage",
    image: `${C7}/derevjannyi-eko-kottedzh-7-photos-big.jpg`,
    images: [
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big.jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(1).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(2).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(3).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(4).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(5).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(6).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(7).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(8).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(9).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(10).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(11).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(12).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(13).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(14).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(15).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(16).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(17).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(18).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(19).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(20).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(21).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(22).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(23).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(24).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(25).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(26).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(27).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(28).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(29).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(30).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(31).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(32).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(33).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(34).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(35).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(36).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(37).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(38).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(39).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(40).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(41).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(42).jpg`,
    ],
    area: 130,
    guests: 6,
    bedrooms: 2,
    description: "Эко коттедж из деревянного бруса с панорамным видом на море. 2 спальни, 2 санузла, открытые террасы, оборудованная кухня.",
    longDescription: "Деревянный эко коттедж №7 площадью 130 м² построен из экологически чистого материала — деревянного бруса. Расположен в коттеджном комплексе «Усадьба VIP» по ул. Звёздная 22, Хоста. Арендуемая часть занимает второй и третий этажи с отдельным входом. В коттедже 2 просторные спальни с большими двуспальными кроватями, 2 санузла с душевыми кабинами, полностью оборудованная кухня с видом на море и уютная гостиная. Открытые террасы и балконы с панорамным видом на Чёрное море. В каждой комнате установлены кондиционеры. Коммунальные платежи включены в стоимость проживания.",
    features: ["Бассейн", "Сауна", "Вид на море", "Барбекю", "Wi-Fi", "Парковка"],
    href: "/cottages/eco-kottedzh-7",
  },
  {
    id: "cottage-10",
    slug: "kottedzh-10",
    title: "Коттедж №10",
    type: "cottage",
    image: `${C10}/eko-kottedzh-10-photos-big.jpg`,
    images: [
      `${C10}/eko-kottedzh-10-photos-big.jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(1).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(2).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(3).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(4).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(5).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(6).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(7).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(8).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(9).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(10).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(11).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(12).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(13).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(14).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(15).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(16).jpg`,
      `${C10}/kottedzh-10-photos-big.jpg`,
      `${C10}/kottedzh-10-photos-big%20(1).jpg`,
      `${C10}/kottedzh-10-photos-big%20(2).jpg`,
      `${C10}/kottedzh-10-photos-big%20(3).jpg`,
      `${C10}/kottedzh-10-photos-big%20(4).jpg`,
      `${C10}/kottedzh-10-photos-big%20(5).jpg`,
      `${C10}/kottedzh-10-photos-big%20(6).jpg`,
    ],
    area: 150,
    guests: 4,
    bedrooms: 2,
    description: "Одноуровневый эко коттедж из деревянного бруса с видом на море. 2 спальни с ваннами, два балкона с видом на море.",
    longDescription: "Коттедж №10 площадью 150 м² — одноуровневый эко коттедж из экологически чистого деревянного бруса с панорамным видом на море и прямым доступом к бассейну. Уютная гостиная совмещена с кухней, 2 спальни с большими двуспальными кроватями, 2 ванные комнаты с ваннами. Два балкона с видом на море. В каждой комнате кондиционер. Вся необходимая мебель и техника включены. Ландшафтный сад с субтропическими и хвойными деревьями.",
    features: ["Бассейн", "Сауна", "Вид на море", "Барбекю", "Wi-Fi", "2 балкона"],
    href: "/cottages/kottedzh-10",
  },
  {
    id: "cottage-5",
    slug: "kottedzh-5",
    title: "Президентский коттедж №5",
    type: "cottage",
    image: `${C5}/prezidentskii-kottedzh-5-photos-big.jpg`,
    images: [
      `${C5}/prezidentskii-kottedzh-5-photos-big.jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(1).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(2).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(3).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(4).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(5).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(6).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(7).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(8).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(9).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(10).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(11).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(12).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(13).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(14).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(15).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(16).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(17).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(18).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(19).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(20).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(21).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(22).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(23).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(24).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(25).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(26).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(27).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(28).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(29).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(30).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(31).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(32).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(33).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(34).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(35).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(36).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(37).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(38).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(39).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(40).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(41).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(42).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(43).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(44).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(45).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(46).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(47).jpg`,
    ],
    area: 282,
    guests: 8,
    bedrooms: 4,
    description: "Просторный коттедж 282 м² с 4 спальнями, камином, 2 террасами с видом на море и подогреваемым бассейном.",
    longDescription: "Президентский коттедж №5 площадью 282 м² — самый просторный объект комплекса «Усадьба VIP». Расположен в закрытом коттеджном посёлке с ландшафтным садом и сезонным открытым подогреваемым бассейном с панорамным видом на море. Четыре спальни и четыре санузла, большая гостиная с камином, полностью оснащённая кухня, прачечная. Две террасы с видом на море. Финская сауна, зона барбекю, приватная парковка. 24/7 видеонаблюдение, охраняемая территория.",
    features: ["Камин", "Сауна", "Бассейн", "2 террасы", "Wi-Fi", "Вид на море"],
    href: "/cottages/kottedzh-5",
  },
  {
    id: "cottage-3",
    slug: "kottedzh-3",
    title: "Коттедж №3",
    type: "cottage",
    image: `${C3}/kottedzh-3-s-vidom-na-more-photos-big.jpg`,
    images: [
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big.jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(1).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(2).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(3).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(4).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(5).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(6).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(7).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(8).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(9).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(10).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(11).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(12).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(13).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(14).jpg`,
      `${C3}/kottedzh-3-photos-big.jpg`,
      `${C3}/kottedzh-3-photos-big%20(1).jpg`,
      `${C3}/kottedzh-3-photos-big%20(2).jpg`,
      `${C3}/kottedzh-3-photos-big%20(3).jpg`,
      `${C3}/kottedzh-3-photos-big%20(4).jpg`,
      `${C3}/kottedzh-3-photos-big%20(5).jpg`,
      `${C3}/kottedzh-3-photos-big%20(6).jpg`,
      `${C3}/kottedzh-3-photos-big%20(7).jpg`,
      `${C3}/kottedzh-3-photos-big%20(8).jpg`,
      `${C3}/kottedzh-3-photos-big%20(9).jpg`,
      `${C3}/kottedzh-3-photos-big%20(10).jpg`,
    ],
    area: 130,
    guests: 6,
    bedrooms: 2,
    description: "Коттедж с панорамным видом на море. 2 спальни, 2 санузла с ваннами, открытые террасы, кухня с видом на море.",
    longDescription: "Коттедж №3 площадью 130 м² с панорамным видом на Чёрное море. Арендуемая часть занимает второй и третий этажи с отдельным входом. Две просторные спальни с двуспальными кроватями, два санузла с ваннами, открытые террасы и балконы с видом на море. Полностью оборудованная кухня с видом на море и уютная гостиная с балконом. В каждой комнате установлен кондиционер. Подогреваемый бассейн с зоной отдыха, зона барбекю, парковочное место, охраняемая территория с видеонаблюдением.",
    features: ["Бассейн", "Сауна", "Вид на море", "Барбекю", "Wi-Fi", "Терраса"],
    href: "/cottages/kottedzh-3",
  },
  {
    id: "cottage-1b",
    slug: "kottedzh-1b",
    title: "Коттедж №1Б",
    type: "cottage",
    image: `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big.jpg`,
    images: [
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big.jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(1).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(2).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(3).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(4).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(5).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(6).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(7).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(8).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(9).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(10).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(11).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(12).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(13).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(14).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(15).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(16).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(17).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(18).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(19).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(20).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(21).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(22).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(23).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(24).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(25).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(26).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(27).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(28).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(29).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(30).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(31).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(32).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(33).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(34).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(35).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(36).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(37).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(38).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(39).jpg`,
    ],
    area: 228,
    guests: 6,
    bedrooms: 3,
    description: "Новый трёхэтажный коттедж с видом на море. 3 спальни с санузлами, тёплый пол, декоративный пруд с карпами кои.",
    longDescription: "Коттедж №1Б — новый трёхэтажный коттедж площадью 228 м² с панорамным видом на море. Современный ремонт с тёплыми полами и сплит-системами в каждой комнате. Три спальни, три санузла, большая кухня-гостиная. На первом этаже — холл с санузлом и спальня; на втором — кухня, санузел и спальня с балконом с видом на море; на третьем — просторная гостиная. На территории комплекса: подогреваемый бассейн, зона барбекю, декоративный пруд с карпами кои, русская баня. Охраняемая закрытая парковка с видеонаблюдением.",
    features: ["Бассейн", "Сауна", "Вид на море", "Wi-Fi", "Пруд с кои", "Тёплый пол"],
    href: "/cottages/kottedzh-1b",
  },
  {
    id: "cottage-2",
    slug: "kottedzh-2",
    title: "Коттедж №2",
    type: "cottage",
    image: `${C2}/kottedzh-2-s-vidom-na-more-photos-big.jpg`,
    images: [
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big.jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(1).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(2).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(3).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(4).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(5).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(6).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(7).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(8).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(9).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(10).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(11).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(12).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(13).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(14).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(15).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(16).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(17).jpg`,
    ],
    area: 130,
    guests: 6,
    bedrooms: 2,
    description: "Коттедж с панорамным видом на море в закрытом комплексе. 2 спальни, открытые террасы, оборудованная кухня.",
    longDescription: "Коттедж №2 площадью 130 м² с панорамным видом на море в закрытом коттеджном комплексе. Арендуемая часть — второй и третий этажи с отдельным входом. Две спальни с большими двуспальными кроватями, два санузла с ваннами, оборудованная кухня с видом на море, открытые террасы и балконы. Кондиционер в каждой комнате. Коммунальные платежи включены в стоимость проживания. Подогреваемый бассейн, зона барбекю, парковочное место.",
    features: ["Бассейн", "Сауна", "Вид на море", "Барбекю", "Wi-Fi", "Терраса"],
    href: "/cottages/kottedzh-2",
  },
];

export const apartments: Property[] = [
  {
    id: "apt-k7",
    slug: "apt-kottedzh-7",
    title: "Апартаменты в коттедже № 7",
    type: "apartment",
    image: `${A7}/apartamenty-7-v-kottedzhe-7-photo-big.jpg`,
    images: [
      `${A7}/apartamenty-7-v-kottedzhe-7-photo-big.jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big.jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(1).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(2).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(3).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(4).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(5).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(6).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(7).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(8).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(9).jpg`,
    ],
    area: 62,
    guests: 4,
    bedrooms: 1,
    description: "Апартаменты 62 м² с видом на море. Новый ремонт, тёплый пол, кухня-гостиная, спальня с двуспальной кроватью, санузел с ванной.",
    longDescription: "Апартаменты площадью 62 м² на первом этаже коттеджа №7 с прямым видом на море. Новый дизайнерский ремонт, тёплый пол, кондиционер. Просторная кухня-гостиная, уютная спальня с двуспальной кроватью, санузел с ванной. Отдельный изолированный вход. Весь комплекс имеет прямой панорамный вид на море. На территории: подогреваемый бассейн, зона барбекю, декоративный пруд с карпами кои, охраняемая закрытая парковка с видеонаблюдением. Коммунальные платежи включены в стоимость.",
    features: ["Вид на море", "Тёплый пол", "Кондиционер", "Wi-Fi", "Бассейн", "Барбекю"],
    href: "/apartments/apt-kottedzh-7",
  },
  {
    id: "apt-k4",
    slug: "apt-kottedzh-4",
    title: "Апартаменты в коттедже № 4",
    type: "apartment",
    image: `${A4}/apartamenty-4-v-kottedzhe-4-photo-big.jpg`,
    images: [
      `${A4}/apartamenty-4-v-kottedzhe-4-photo-big.jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big.jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(1).jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(2).jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(3).jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(4).jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(5).jpg`,
    ],
    area: 62,
    guests: 4,
    bedrooms: 1,
    description: "Апартаменты 62 м² с видом на море. Новый ремонт, тёплый пол, кухня-гостиная, спальня с двуспальной кроватью.",
    longDescription: "Апартаменты площадью 62 м² на первом этаже коттеджа №4 с видом на море. Новый ремонт, тёплый пол, кондиционер. Просторная кухня-гостиная, спальня с двуспальной кроватью, санузел с ванной. Отдельный изолированный вход. На территории комплекса: подогреваемый бассейн, зона барбекю, русская баня. Охраняемая закрытая парковка с видеонаблюдением, 24/7 охрана. Wi-Fi и вся необходимая мебель и техника включены.",
    features: ["Вид на море", "Тёплый пол", "Кондиционер", "Wi-Fi", "Бассейн", "Парковка"],
    href: "/apartments/apt-kottedzh-4",
  },
  {
    id: "apt-k5-2",
    slug: "apt-kottedzh-5-2",
    title: "Апартаменты в коттедже №5-2",
    type: "apartment",
    image: `${A52}/5f526e52.jpg`,
    images: [
      `${A52}/5f526e52.jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big.jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(1).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(2).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(3).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(4).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(5).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(6).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(7).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(8).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(9).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(10).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(11).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(12).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(13).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(14).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(15).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(16).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(17).jpg`,
    ],
    area: 64,
    guests: 4,
    bedrooms: 1,
    description: "Апартаменты 64 м² с видом на море. Спальня с джакузи, кухня-гостиная, душевая кабина. Идеально для романтического отдыха.",
    longDescription: "Апартаменты площадью 64 м² с видом на море в коттедже №5. Расположены на первом этаже с отдельным изолированным входом. Уютная кухня-гостиная, спальня с джакузи, санузел с душевой кабиной. Все необходимые мебель и техника, Wi-Fi. На территории: подогреваемый бассейн, ухоженный газон, зона барбекю с видом на море, деревянная баня. Охраняемая парковка, 24/7 видеонаблюдение.",
    features: ["Вид на море", "Джакузи", "Кондиционер", "Wi-Fi", "Бассейн", "Барбекю"],
    href: "/apartments/apt-kottedzh-5-2",
  },
  {
    id: "apt-k5-1",
    slug: "apt-kottedzh-5-1",
    title: "Апартаменты в коттедже №5-1",
    type: "apartment",
    image: `${A51}/apartamenty-v-kottedzhe-5-1-photo-big.jpg`,
    images: [
      `${A51}/apartamenty-v-kottedzhe-5-1-photo-big.jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big.jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(1).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(2).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(3).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(4).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(5).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(6).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(7).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(8).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(9).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(10).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(11).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(12).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(13).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(14).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(15).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(16).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(17).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(18).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(19).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(20).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(21).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(22).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(23).jpg`,
    ],
    area: 64,
    guests: 4,
    bedrooms: 1,
    description: "Апартаменты 64 м² с видом на море. Спальня с джакузи, отдельный вход, закрытая охраняемая территория.",
    longDescription: "Апартаменты площадью 64 м² с видом на море в коттедже №5. Первый этаж, собственный изолированный вход. Кухня совмещена с гостиной, просторная спальня с джакузи, санузел с душевой кабиной. Вся мебель и техника включены, Wi-Fi. Комплекс «Усадьба VIP»: подогреваемый бассейн, ухоженный газон, зона барбекю с видом на море, деревянная баня. Охраняемая парковка с видеонаблюдением, 24/7 охрана.",
    features: ["Вид на море", "Джакузи", "Кондиционер", "Wi-Fi", "Бассейн", "Охрана"],
    href: "/apartments/apt-kottedzh-5-1",
  },
  {
    id: "apt-k2",
    slug: "apt-kottedzh-2",
    title: "Апартаменты в коттедже №2",
    type: "apartment",
    image: `${A2}/apartamenty-v-kottedzhe-2-photo-big.jpg`,
    images: [
      `${A2}/apartamenty-v-kottedzhe-2-photo-big.jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big.jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(1).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(2).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(3).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(4).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(5).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(6).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(7).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(8).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(9).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(10).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(11).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(12).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(13).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(14).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(15).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(16).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(17).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(18).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(19).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(20).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(21).jpg`,
    ],
    area: 62,
    guests: 4,
    bedrooms: 1,
    description: "Апартаменты 62 м² с видом на море, первый этаж, отдельный вход. Новый ремонт, тёплый пол, кондиционер.",
    longDescription: "Апартаменты площадью 62 м² с видом на море в коттедже №2. Расположены на первом этаже с отдельным входом. Новый ремонт, тёплый пол, кондиционер. Большая кухня-гостиная, спальня с двуспальной кроватью, санузел с ванной. Вся мебель и техника новые, Wi-Fi. На территории комплекса: подогреваемый бассейн, зона барбекю, русская баня. Охраняемая парковка, 24/7 видеонаблюдение.",
    features: ["Вид на море", "Тёплый пол", "Кондиционер", "Wi-Fi", "Бассейн", "Барбекю"],
    href: "/apartments/apt-kottedzh-2",
  },
  {
    id: "apt-k3",
    slug: "apt-kottedzh-3",
    title: "Апартаменты в коттедже №3",
    type: "apartment",
    image: `${A3}/apartamenty-3-photo-big.jpg`,
    images: [
      `${A3}/apartamenty-3-photo-big.jpg`,
      `${A3}/apartamenty-3-photos-big.jpg`,
      `${A3}/apartamenty-3-photos-big%20(1).jpg`,
      `${A3}/apartamenty-3-photos-big%20(2).jpg`,
      `${A3}/apartamenty-3-photos-big%20(3).jpg`,
      `${A3}/apartamenty-3-photos-big%20(4).jpg`,
      `${A3}/apartamenty-3-photos-big%20(5).jpg`,
      `${A3}/apartamenty-3-photos-big%20(6).jpg`,
      `${A3}/apartamenty-3-photos-big%20(7).jpg`,
      `${A3}/apartamenty-3-photos-big%20(8).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big.jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(1).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(2).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(3).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(4).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(5).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(6).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(7).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(8).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(9).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(10).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(11).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(12).jpg`,
    ],
    area: 60,
    guests: 4,
    bedrooms: 1,
    description: "Апартаменты 60 м² с панорамным видом на море. Кухня-гостиная, спальня, душевая кабина, отдельный вход.",
    longDescription: "Апартаменты площадью 60 м² с видом на море в коттедже №3. Расположены на первом этаже с собственным изолированным входом. Просторная кухня-гостиная, спальня с двуспальной кроватью, санузел с душем. Вся необходимая мебель, техника и Wi-Fi. Весь комплекс имеет прямой вид на море. На территории: подогреваемый бассейн, ухоженный газон, зона барбекю с видом на море, русская баня. Охраняемая парковка, 24/7 видеонаблюдение.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Бассейн", "Барбекю", "Парковка"],
    href: "/apartments/apt-kottedzh-3",
  },
];

export const flats: Property[] = [
  {
    id: "flat-golland-6-2",
    slug: "flat-gollandskii-6-2",
    title: "Квартира №6-2 ЖК «Голландский»",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(8).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Уютная квартира с дизайнерским ремонтом и видом на море. 2-й этаж, отдельная спальня, витражное остекление.",
    longDescription: "Уютная квартира №6-2 в ЖК «Голландский» по ул. Звёздная 22 (совхоз Приморский, Хоста). Расположена на 2-м этаже с витражным остеклением и видом на море. Новый ремонт, вся мебель и техника новые. Выделенная спальня, кухня с необходимой техникой (плита, духовка, холодильник), кондиционер, постельное бельё, посуда. Охраняемая закрытая территория. Минимальный срок аренды — 5 дней.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Охрана", "Новый ремонт"],
    href: "/flats/flat-gollandskii-6-2",
  },
  {
    id: "flat-golland-5",
    slug: "flat-gollandskii-5",
    title: "Квартира №5 ЖК «Голландский»",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(11).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира с дизайнерским ремонтом и видом на море. 1-й этаж, панорамное остекление, тёплый пол, выделенная парковка.",
    longDescription: "Квартира №5 в ЖК «Голландский» по ул. Звёздная 22 (совхоз Приморский, Хоста). Расположена на 1-м этаже с панорамным остеклением и видом на море. Дизайнерский ремонт, новая мебель и техника, тёплый пол. Выделенная зонированная спальня, современная кухня, кондиционер. Выделенная парковка. Охраняемая закрытая территория.",
    features: ["Вид на море", "Тёплый пол", "Wi-Fi", "Парковка", "Дизайн-ремонт", "Охрана"],
    href: "/flats/flat-gollandskii-5",
  },
  {
    id: "flat-zvezdnaya-8-17",
    slug: "flat-zvezdnaya-8-17",
    title: "Квартира №8 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(11).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира-студия в клубном доме с видом на море. Гостиная с кухней, выделенная спальня, крытая парковка.",
    longDescription: "Квартира №8 в клубном доме по ул. Звёздная 22-17 (Хостинский район). Гостиная совмещена с кухней, выделенная спальня, современный ремонт. Вид на море, крытая парковка включена, Wi-Fi. Закрытая охраняемая территория. Вся необходимая мебель и техника.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Закрытая территория"],
    href: "/flats/flat-zvezdnaya-8-17",
  },
  {
    id: "flat-zvezdnaya-2-17",
    slug: "flat-zvezdnaya-2-17",
    title: "Квартира №2 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(7).jpg`,
    ],
    area: 22,
    guests: 2,
    bedrooms: 1,
    description: "Квартира-студия 22 м² в клубном доме, 1-й этаж. Новый ремонт, вся техника и мебель, Wi-Fi, парковка.",
    longDescription: "Квартира-студия №2 в клубном доме по ул. Звёздная 22-17 (совхоз Приморский, Хоста). Фактическая площадь 22 м², 1-й этаж. Новый ремонт, новые мебель и техника, Wi-Fi. Крытая парковка, закрытая охраняемая территория с видеонаблюдением. Развитая инфраструктура рядом: магазины, остановки общественного транспорта.",
    features: ["Кондиционер", "Wi-Fi", "Парковка", "Новый ремонт", "Охрана"],
    href: "/flats/flat-zvezdnaya-2-17",
  },
  {
    id: "flat-zvezdnaya-5-17",
    slug: "flat-zvezdnaya-5-17",
    title: "Квартира №5 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(12).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 35 м² с изолированной спальней в клубном доме. 3-й этаж, вид на море с балкона, подземная парковка.",
    longDescription: "Квартира №5 с изолированной спальней в клубном доме по ул. Звёздная 22-17 (совхоз Приморский, Хоста). Фактическая площадь 35 м² + открытый балкон 9 м² с видом на море. 3-й этаж. Новая мебель и техника, Wi-Fi. Подземная парковка, закрытая охраняемая территория. Рядом магазины, остановки.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Подземная парковка", "Балкон", "Охрана"],
    href: "/flats/flat-zvezdnaya-5-17",
  },
  {
    id: "flat-zvezdnaya-1-17",
    slug: "flat-zvezdnaya-1-17",
    title: "Квартира №1 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-17/kvartira-1-ul-zvezdnaja-22-17-photos-big%20(8).jpg`,
    ],
    area: 24,
    guests: 2,
    bedrooms: 1,
    description: "Квартира-студия 24 м² в клубном доме, 1-й этаж. Новый ремонт, вид на море из окон, подземная парковка.",
    longDescription: "Квартира-студия №1 в клубном доме по ул. Звёздная 22-17 (совхоз Приморский, Хоста). Фактическая площадь 24 м², 1-й этаж. Новый ремонт, все мебель и техника новые, Wi-Fi. Вид на море из окон. Подземная парковка, закрытая охраняемая территория с видеонаблюдением. Рядом магазины, остановки.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Новый ремонт"],
    href: "/flats/flat-zvezdnaya-1-17",
  },
  {
    id: "flat-zvezdnaya-4-17",
    slug: "flat-zvezdnaya-4-17",
    title: "Квартира №4 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(13).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(14).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(15).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(16).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 35 м² в клубном доме, 2-й этаж. Вид на море с балкона, новый ремонт, подземная парковка.",
    longDescription: "Квартира №4 в клубном доме по ул. Звёздная 22-17 (совхоз Приморский, Хоста). Фактическая площадь 35 м² + открытый балкон 9 м² с видом на море. 2-й этаж. Новая мебель и техника, Wi-Fi. Подземная парковка, закрытая охраняемая территория. Развитая инфраструктура рядом.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Подземная парковка", "Балкон"],
    href: "/flats/flat-zvezdnaya-4-17",
  },
  {
    id: "flat-zvezdnaya-6-17",
    slug: "flat-zvezdnaya-6-17",
    title: "Квартира №6 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/9fab1d8b.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/9fab1d8b.jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-6-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-6-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-6-ul.-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%206%20zvezdnaya%2022-17/kvartira-4-ul.-22-17-photos-big%20(13).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 35 м² в клубном доме, 2-й этаж. Вид на море с балкона, новый ремонт, подземная парковка.",
    longDescription: "Квартира №6 в клубном доме по ул. Звёздная 22-17 (совхоз Приморский, Хоста). Фактическая площадь 35 м² + открытый балкон 9 м² с видом на море. 2-й этаж. Новая мебель и техника, Wi-Fi. Подземная парковка, закрытая охраняемая территория. Развитая инфраструктура рядом.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Подземная парковка", "Балкон"],
    href: "/flats/flat-zvezdnaya-6-17",
  },
  {
    id: "flat-zvezdnaya-3-17",
    slug: "flat-zvezdnaya-3-17",
    title: "Квартира №3 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-3-ul-zvezdnaja-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-3-ul-zvezdnaja-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-3-ul-zvezdnaja-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-3-ul-zvezdnaja-22-17-photos-big%20(3).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 35 м² в клубном доме, 2-й этаж. Вид на море с балкона, новый ремонт, подземная парковка.",
    longDescription: "Квартира №3 в клубном доме по ул. Звёздная 22-17 (совхоз Приморский, Хоста). Фактическая площадь 35 м² + открытый балкон 9 м² с видом на море. 2-й этаж. Новая мебель и техника, Wi-Fi. Подземная парковка, закрытая охраняемая территория. Рядом магазины и остановки транспорта.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Подземная парковка", "Балкон"],
    href: "/flats/flat-zvezdnaya-3-17",
  },
  {
    id: "flat-zvezdnaya-4-16",
    slug: "flat-zvezdnaya-4-16",
    title: "Квартира №4 ул. Звёздная 22-16",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/9c910700.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/9c910700.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(13).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(14).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(15).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(16).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(17).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(18).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(19).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(20).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(21).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(22).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 35 м² в клубном доме, 2-й этаж. Вид на море с балкона, новый ремонт, подземная парковка.",
    longDescription: "Квартира-студия №4 в клубном доме по ул. Звёздная 22-16 (совхоз Приморский, Хоста). Фактическая площадь 35 м² + балкон 8 м² с видом на море. 2-й этаж. Новый ремонт, новые мебель и техника, Wi-Fi. Подземная парковка, закрытая охраняемая территория. Рядом магазины, остановки.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Подземная парковка", "Балкон"],
    href: "/flats/flat-zvezdnaya-4-16",
  },
  {
    id: "flat-zvezdnaya-2-16",
    slug: "flat-zvezdnaya-2-16",
    title: "Квартира №2 ул. Звёздная 22-16",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/c9dfb3eb.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/c9dfb3eb.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(13).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(14).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(15).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(16).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(17).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 35 м² в клубном доме, 1-й этаж. Вид на море из окон, новый ремонт, подземная парковка.",
    longDescription: "Квартира-студия №2 в клубном доме по ул. Звёздная 22-16 (совхоз Приморский, Хоста). Фактическая площадь 35 м² + балкон 8 м² с видом на море. 1-й этаж. Новый ремонт, новые мебель и техника, Wi-Fi. Подземная парковка, закрытая охраняемая территория. Рядом магазины, остановки.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Подземная парковка", "Балкон"],
    href: "/flats/flat-zvezdnaya-2-16",
  },
];

export const allProperties = [...cottages, ...apartments, ...flats];

export const reviews = [
  {
    id: 1,
    name: "Анна К.",
    date: "Август 2024",
    rating: 5,
    text: "Провели незабываемый отпуск! Коттедж превзошёл все ожидания — чистота, уют, потрясающий вид на море. Персонал очень внимательный и отзывчивый. Обязательно вернёмся!",
    property: "Деревянный эко коттедж №7",
  },
  {
    id: 2,
    name: "Дмитрий В.",
    date: "Июль 2024",
    rating: 5,
    text: "Отличное место для семейного отдыха. Дети были в восторге от бассейна. Расположение очень удобное — до моря 5 минут пешком.",
    property: "Коттедж №10",
  },
  {
    id: 3,
    name: "Елена и Михаил С.",
    date: "Июнь 2024",
    rating: 5,
    text: "Апартаменты выше всяких похвал! Дизайн на высшем уровне, всё продумано до мелочей. Вид с балкона — просто сказка. Спасибо за тёплый приём!",
    property: "Апартаменты в коттедже №5-2",
  },
  {
    id: 4,
    name: "Сергей Т.",
    date: "Май 2024",
    rating: 5,
    text: "Снимали Президентский коттедж на корпоратив. Всё прошло на высшем уровне — пространство идеальное, кухня полностью оснащена. Рекомендую!",
    property: "Президентский коттедж №5",
  },
  {
    id: 5,
    name: "Ирина Л.",
    date: "Сентябрь 2024",
    rating: 5,
    text: "Отдыхала с подругами, взяли апартаменты с джакузи. Очень романтичная обстановка, продуманный интерьер. Хозяева встретили с теплом. Советую всем!",
    property: "Апартаменты в коттедже №5-1",
  },
  {
    id: 6,
    name: "Алексей Н.",
    date: "Октябрь 2024",
    rating: 5,
    text: "Были с семьёй во второй раз — снова в полном восторге. Это место действительно заслуживает звания VIP. Спасибо команде за высокий уровень сервиса!",
    property: "Коттедж №1Б",
  },
];

export const newsItems = [
  {
    id: 1,
    title: "Новый сезон 2025: открытие бронирования",
    date: "15 января 2025",
    category: "Новости",
    image: `${BASE}/upload/000/u1/c/7/a0fd6e0d.jpg`,
    excerpt:
      "Рады сообщить об открытии бронирования на летний сезон 2025. Новые предложения, специальные тарифы для постоянных гостей.",
  },
  {
    id: 2,
    title: "Реновация бассейна завершена",
    date: "10 декабря 2024",
    category: "Обновления",
    image: `${BASE}/upload/000/u1/4/2/b14adbcc.jpg`,
    excerpt:
      "Мы полностью обновили бассейн: установлена современная система очистки, добавлена подсветка и зона релакса.",
  },
  {
    id: 3,
    title: "Скидки 20% на сентябрь и октябрь",
    date: "01 августа 2024",
    category: "Акции",
    image: `${BASE}/upload/000/u2/4/b/4ba2d64e.jpg`,
    excerpt:
      "Бархатный сезон — лучшее время для отдыха на море! Специальные цены на все объекты комплекса в сентябре и октябре.",
  },
];

const TC = `${BASE}/Usadba/territory/territory_cottages`;
const TT = `${BASE}/Usadba/territory/territory_teatralnaya_11`;
const TZ16 = `${BASE}/Usadba/territory/territory_zvezdnaya%2022-16%20Magnolia`;
const TZ17 = `${BASE}/Usadba/territory/territory_zvezdnaya%2022-17`;

export const galleryImages = [
  // Коттеджи
  { src: `${C7}/derevjannyi-eko-kottedzh-7-photos-big.jpg`, alt: "Деревянный эко коттедж №7", category: "Коттеджи" },
  { src: `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(1).jpg`, alt: "Эко коттедж №7", category: "Коттеджи" },
  { src: `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(5).jpg`, alt: "Эко коттедж №7 терраса", category: "Коттеджи" },
  { src: `${C10}/eko-kottedzh-10-photos-big.jpg`, alt: "Коттедж №10", category: "Коттеджи" },
  { src: `${C10}/kottedzh-10-photos-big%20(1).jpg`, alt: "Коттедж №10 интерьер", category: "Коттеджи" },
  { src: `${C5}/prezidentskii-kottedzh-5-photos-big.jpg`, alt: "Президентский коттедж №5", category: "Коттеджи" },
  { src: `${C5}/prezidentskii-kottedzh-5-photos-big%20(1).jpg`, alt: "Коттедж №5 интерьер", category: "Коттеджи" },
  { src: `${C3}/kottedzh-3-s-vidom-na-more-photos-big.jpg`, alt: "Коттедж №3 вид на море", category: "Коттеджи" },
  { src: `${C3}/kottedzh-3-photos-big%20(1).jpg`, alt: "Коттедж №3 интерьер", category: "Коттеджи" },
  { src: `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big.jpg`, alt: "Коттедж №1Б", category: "Коттеджи" },
  { src: `${C2}/kottedzh-2-s-vidom-na-more-photos-big.jpg`, alt: "Коттедж №2", category: "Коттеджи" },
  // Апартаменты
  { src: `${A7}/apartamenty-7-v-kottedzhe-7-photo-big.jpg`, alt: "Апартаменты в коттедже №7", category: "Апартаменты" },
  { src: `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(1).jpg`, alt: "Апартаменты №7 гостиная", category: "Апартаменты" },
  { src: `${A4}/apartamenty-4-v-kottedzhe-4-photo-big.jpg`, alt: "Апартаменты в коттедже №4", category: "Апартаменты" },
  { src: `${A52}/5f526e52.jpg`, alt: "Апартаменты в коттедже №5-2", category: "Апартаменты" },
  { src: `${A51}/apartamenty-v-kottedzhe-5-1-photo-big.jpg`, alt: "Апартаменты в коттедже №5-1", category: "Апартаменты" },
  { src: `${A2}/apartamenty-v-kottedzhe-2-photo-big.jpg`, alt: "Апартаменты в коттедже №2", category: "Апартаменты" },
  { src: `${A3}/apartamenty-3-photo-big.jpg`, alt: "Апартаменты в коттедже №3", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photo-big.jpg`, alt: "Квартира ЖК Голландский №6-2", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photo-big.jpg`, alt: "Квартира ЖК Голландский №5", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photo-big.jpg`, alt: "Квартира ул. Звёздная 22-17 №8", category: "Апартаменты" },
  // Территория коттеджного комплекса
  { src: `${TC}/00c3af2c.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/0607cf06.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/0c6b8a33.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/117700bf.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/11ca9002.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/145e1b78.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/14bcb8e3.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/2b609a52.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/374a3992.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/3c45aa66.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/46c8b8fb.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/4ada4ea4.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/4fd0b0b2.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/50a7382d.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/54473f6c.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/6092a2d8.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/7593f114.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/97a7f7d9.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/98310ec8.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a6b6db7d.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a85b6e42.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a878fceb.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a91ad334.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a963d010.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/b2040183.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/b2ee642a.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/bc45b94a.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/c229e13f.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/c7047a07.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/c9217d58.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/e4a6f70b.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/e64487f5.jpg`, alt: "Территория комплекса", category: "Территория" },
  // ул. Театральная д.11
  { src: `${TT}/32436db7.jpg`, alt: "ул. Театральная д.11", category: "Территория" },
  { src: `${TT}/336bfad2.jpg`, alt: "ул. Театральная д.11", category: "Территория" },
  { src: `${TT}/47df81bc.jpg`, alt: "ул. Театральная д.11", category: "Территория" },
  // ЖК Магнолия ул. Звёздная 22-16
  { src: `${TZ16}/100579ac.jpg`, alt: "ЖК Магнолия ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/2f4a48d1.jpg`, alt: "ЖК Магнолия ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/4ebe94f7.jpg`, alt: "ЖК Магнолия ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/705f7e35.jpg`, alt: "ЖК Магнолия ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/88170944.jpg`, alt: "ЖК Магнолия ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/d487bc4c.jpg`, alt: "ЖК Магнолия ул. Звёздная 22-16", category: "Территория" },
  // ул. Звёздная 22-17
  { src: `${TZ17}/12eb3e23.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
  { src: `${TZ17}/31061044.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
  { src: `${TZ17}/e352f0d8.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
  { src: `${TZ17}/faddbb8b.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
];
