import type { Property } from "@/components/PropertyCard";

const BASE = process.env.NEXT_PUBLIC_BASE_PATH || "";
const C7 = `${BASE}/Usadba/cottages/cottage%207`;
const C10 = `${BASE}/Usadba/cottages/cottage%2010`;
const C5 = `${BASE}/Usadba/cottages/cottage%205`;
const C3 = `${BASE}/Usadba/cottages/cottage%203`;
const C1B = `${BASE}/Usadba/cottages/cottage%201-B`;
const C2 = `${BASE}/Usadba/cottages/cottage%202`;
const C4 = `${BASE}/Usadba/cottages/cottage%204`;
const A7 = `${BASE}/Usadba/apartments/apartments%207`;
const A4 = `${BASE}/Usadba/apartments/apartments%204`;
const A52 = `${BASE}/Usadba/apartments/apartments%205-2`;
const A51 = `${BASE}/Usadba/apartments/apartments%205-1`;
const A2 = `${BASE}/Usadba/apartments/apartments%202`;
const A3 = `${BASE}/Usadba/apartments/apartments%203`;

export const cottages: Property[] = [
  {
    id: "cottage-eco7",
    slug: "eco-kottedzh-7",
    title: "Деревянный эко коттедж №7",
    type: "cottage",
    image: `${C7}/derevjannyi-eko-kottedzh-7-photos-big.jpg`,
    images: [
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big.jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(1).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(2).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(3).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(4).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(16).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(17).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(18).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(19).jpg`,
      `${C7}/photo_2026-04-07_21-43-33.jpg`,
      `${C7}/photo_2026-04-07_21-43-41.jpg`,
      `${C7}/photo_2026-04-07_21-43-44.jpg`,
      `${C7}/photo_2026-04-07_21-43-46.jpg`,
      `${C7}/photo_2026-04-07_21-43-49.jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(20).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(21).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(22).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(23).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(24).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(26).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(27).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(28).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(30).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(31).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(32).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(33).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(34).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(35).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(36).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(37).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(38).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(39).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(40).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(41).jpg`,
      `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(42).jpg`,
    ],
    area: 130,
    guests: 4,
    bedrooms: 2,
    description: "Эко коттедж из деревянного бруса. Открытая терраса с панорамным видом на море. 2 спальни, 3 санузла.",
    longDescription: "Деревянный эко коттедж №7 площадью 130 м² построен из экологически чистого материала — деревянного бруса. Расположен в коттеджном комплексе «Усадьба» по ул. Звёздная 22, Хостинский район. Арендуемая часть занимает второй и третий этажи с отдельным входом. В коттедже уютная гостиная, отдельная кухня с обеденной зоной, 2 просторные спальни с санузлами. Есть возможность размещения дополнительно двух гостей. Открытая терраса и балконы с панорамным видом на Чёрное море. Коттедж оборудован всей необходимой техникой и мебелью для комфортного проживания. Ландшафтный дизайн, зона барбекю, декоративный пруд с карпами, русская баня на дровах, открытый бассейн. Крытая парковка, круглосуточное видеонаблюдение и охрана.",
    features: ["Бассейн", "Русская баня", "Вид на море", "Зона барбекю", "Wi-Fi", "Парковка"],
    price: 17000,
    price14days: 150000,
    priceMonth: 270000,
    price11months: 200000,
    href: "/cottages/eco-kottedzh-7",
  },
  {
    id: "cottage-10",
    slug: "kottedzh-10",
    title: "Коттедж №10",
    type: "cottage",
    image: `${C10}/eko-kottedzh-10-photos-big.jpg`,
    images: [
      `${C10}/eko-kottedzh-10-photos-big.jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(1).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(2).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(3).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(4).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(5).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(6).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(7).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(8).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(9).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(10).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(11).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(12).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(13).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(14).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(15).jpg`,
      `${C10}/eko-kottedzh-10-photos-big%20(16).jpg`,
      `${C10}/kottedzh-10-photos-big.jpg`,
      `${C10}/kottedzh-10-photos-big%20(1).jpg`,
      `${C10}/kottedzh-10-photos-big%20(2).jpg`,
      `${C10}/kottedzh-10-photos-big%20(3).jpg`,
      `${C10}/kottedzh-10-photos-big%20(4).jpg`,
      `${C10}/kottedzh-10-photos-big%20(6).jpg`,
    ],
    area: 150,
    guests: 4,
    bedrooms: 2,
    description: "Одноуровневый эко коттедж из деревянного бруса с видом на море. Уютная гостиная совмещена с кухней, 2 спальни с санузлами и балконами.",
    longDescription: "Коттедж №10 площадью 150 м² — одноуровневый эко коттедж из экологически чистого деревянного бруса с панорамным видом на море и прямым доступом к бассейну. В коттедже — уютная гостиная, совмещённая с кухней. 2 большие спальни, каждая оснащена санузлом, гардеробной и балконом с видом на море. Коттедж оборудован всей необходимой техникой и мебелью для комфортного проживания. Есть возможность размещения дополнительно одного гостя. Ландшафтный дизайн, зона барбекю, декоративный пруд с карпами, русская баня на дровах, открытый бассейн. Круглосуточное видеонаблюдение и охрана. Крытая парковка.",
    features: ["Бассейн", "Русская баня", "Вид на море", "Зона барбекю", "Wi-Fi", "2 балкона"],
    price: 21000,
    price14days: 200000,
    priceMonth: 320000,
    price11months: 230000,
    href: "/cottages/kottedzh-10",
  },
  {
    id: "cottage-5",
    slug: "kottedzh-5",
    title: "Президентский коттедж №5",
    type: "cottage",
    image: `${C5}/prezidentskii-kottedzh-5-photos-big.jpg`,
    images: [
      `${C5}/prezidentskii-kottedzh-5-photos-big.jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(1).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(2).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(3).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(4).jpg`,
      `${C5}/gostinaya-lestnitsa.jpg`,
      `${C5}/gostinaya-kamin-kuhnya.jpg`,
      `${C5}/gostinaya-kuhnya.jpg`,
      `${C5}/gostinaya-divany.jpg`,
      `${C5}/lyustra-kovka.jpg`,
      `${C5}/stolovaya-lyustra.jpg`,
      `${C5}/stolovaya-sverkhu.jpg`,
      `${C5}/kuhnya-belaya.jpg`,
      `${C5}/kuhnya-belaya-2.jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(7).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(10).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(11).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(12).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(13).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(14).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(15).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(16).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(17).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(18).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(19).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(20).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(21).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(22).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(23).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(24).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(25).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(26).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(27).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(28).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(29).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(30).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(31).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(32).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(43).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(45).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(46).jpg`,
      `${C5}/prezidentskii-kottedzh-5-photos-big%20(47).jpg`,
    ],
    area: 282,
    guests: 8,
    bedrooms: 4,
    description: "Просторный двухэтажный коттедж, большая гостиная с камином, панорамный вид на море, уютные 4 спальни.",
    longDescription: "Президентский коттедж №5 площадью 282 м² — самый просторный объект комплекса «Усадьба». Расположен в закрытом коттеджном посёлке с ландшафтным садом и открытым бассейном с панорамным видом на море. Четыре уютные спальни с санузлами, большая гостиная с камином и кухонной зоной. Террасы с панорамным видом на море. Коттедж оборудован мебелью и техникой для комфортного проживания и отдыха, имеет возможность размещения двух дополнительных мест для проживания. Ландшафтный дизайн, зона барбекю, декоративный пруд с карпами, русская баня на дровах, открытый бассейн. Круглосуточное видеонаблюдение и охрана. Крытая парковка.",
    features: ["Камин", "Русская баня", "Бассейн", "Wi-Fi", "Вид на море"],
    price: 30000,
    price14days: 260000,
    priceMonth: 450000,
    price11months: 350000,
    href: "/cottages/kottedzh-5",
  },
  {
    id: "cottage-3",
    slug: "kottedzh-3",
    title: "Коттедж №3",
    type: "cottage",
    image: `${C3}/kottedzh-3-s-vidom-na-more-photos-big.jpg`,
    images: [
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big.jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(1).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(3).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(4).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(5).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(7).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(8).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(9).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(10).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(11).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(12).jpg`,
      `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(14).jpg`,
      `${C3}/kottedzh-3-photos-big%20(1).jpg`,
      `${C3}/kottedzh-3-photos-big%20(2).jpg`,
      `${C3}/kottedzh-3-photos-big%20(3).jpg`,
      `${C3}/kottedzh-3-photos-big%20(4).jpg`,
      `${C3}/kottedzh-3-photos-big%20(5).jpg`,
      `${C3}/kottedzh-3-photos-big%20(6).jpg`,
      `${C3}/kottedzh-3-photos-big%20(7).jpg`,
      `${C3}/kottedzh-3-photos-big%20(8).jpg`,
      `${C3}/kottedzh-3-photos-big%20(9).jpg`,
      `${C3}/kottedzh-3-photos-big%20(10).jpg`,
    ],
    area: 130,
    guests: 4,
    bedrooms: 2,
    description: "Коттедж двухэтажный с панорамным видом на море. 2 спальни с санузлами, терраса, гостиная с балконом, кухня.",
    longDescription: "Коттедж №3 площадью 130 м² с панорамным видом на Чёрное море. Арендуемая часть занимает второй и третий этажи с отдельным входом. Две просторные спальни с санузлами. Открытая терраса с видом на море. Уютная гостиная с балконом. Функциональная кухня с обеденной зоной. Есть возможность размещения двух дополнительных мест для проживания. Коттедж имеет своё парковочное место для 1 автомобиля. На территории комплекса расположены: русская баня, бассейн, зона барбекю, декоративный пруд. Круглосуточная охрана с видеонаблюдением. Крытая парковка.",
    features: ["Бассейн", "Русская баня", "Вид на море", "Зона барбекю", "Wi-Fi", "Парковка у дома"],
    price: 18000,
    price14days: 160000,
    priceMonth: 280000,
    price11months: 210000,
    href: "/cottages/kottedzh-3",
  },
  {
    id: "cottage-1b",
    slug: "kottedzh-1b",
    title: "Коттедж №1Б",
    type: "cottage",
    image: `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big.jpg`,
    images: [
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big.jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(1).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(2).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(3).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(4).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(5).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(6).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(7).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(8).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(9).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(10).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(11).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(12).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(13).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(14).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(15).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(16).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(17).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(18).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(19).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(20).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(21).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(22).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(23).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(24).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(25).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(26).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(27).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(28).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(29).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(30).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(31).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(32).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(33).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(34).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(35).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(36).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(37).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(38).jpg`,
      `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(39).jpg`,
    ],
    area: 228,
    guests: 4,
    bedrooms: 2,
    description: "Большой трёхэтажный коттедж с видом на море. 2 спальни с санузлами, тёплый пол, мансарда.",
    longDescription: "Коттедж №1Б — большой трёхэтажный коттедж площадью 228 м² с панорамным видом на море. Современный ремонт. На первом этаже коттеджа — холл с санузлом и спальня. На втором — кухня с балконом, санузел, спальня. Каждая спальня имеет свой санузел и гардеробную. На третьем — мансарда в виде свободного пространства. Коттедж оборудован мебелью и техникой для комфортного проживания и отдыха. Коттедж имеет своё парковочное место на 2 автомобиля. На территории комплекса расположены: русская баня, бассейн, зона барбекю, декоративный пруд. Круглосуточная охрана с видеонаблюдением. Крытая парковка.",
    features: ["Бассейн", "Русская баня", "Вид на море", "Wi-Fi", "Парковка у дома", "Тёплый пол"],
    price: 20000,
    price14days: 180000,
    priceMonth: 300000,
    price11months: 250000,
    href: "/cottages/kottedzh-1b",
  },
  {
    id: "cottage-2",
    slug: "kottedzh-2",
    title: "Коттедж №2",
    type: "cottage",
    image: `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(2).jpg`,
    images: [
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(2).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(3).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(4).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(5).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(6).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(7).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(8).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(9).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(10).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(11).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(12).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(13).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(14).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(15).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(16).jpg`,
      `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(17).jpg`,
      `${C2}/photo_2026-04-01_09-21-56.jpg`,
      `${C2}/photo_2026-04-01_09-22-10.jpg`,
      `${C2}/photo_2026-04-01_09-22-14.jpg`,
      `${C2}/photo_2026-04-01_09-22-17.jpg`,
      `${C2}/photo_2026-04-01_09-22-21.jpg`,
      `${C2}/photo_2026-04-01_09-22-25.jpg`,
    ],
    area: 130,
    guests: 4,
    bedrooms: 2,
    description: "Коттедж двухэтажный с панорамным видом на море. 2 спальни с санузлами, терраса, кухня с видом на море.",
    longDescription: "Коттедж №2 площадью 130 м² с панорамным видом на море. Арендуемая часть — второй и третий этажи с отдельным входом. На нижнем этаже коттеджа — открытая терраса с видом на море. Уютная гостиная с балконом. Функциональная кухня с обеденной зоной. На верхнем этаже — две просторные спальни с санузлом. Коттедж оборудован мебелью и техникой для комфортного проживания и отдыха. Есть возможность размещения двух дополнительных мест для проживания. На территории комплекса расположены: русская баня, бассейн, зона барбекю, декоративный пруд. Круглосуточная охрана с видеонаблюдением. Крытая парковка.",
    features: ["Бассейн", "Русская баня", "Вид на море", "Зона барбекю", "Wi-Fi", "Терраса"],
    price: 13000,
    price14days: 130000,
    priceMonth: 230000,
    price11months: 150000,
    href: "/cottages/kottedzh-2",
  },
  {
    id: "cottage-4",
    slug: "kottedzh-4",
    title: "Коттедж №4",
    type: "cottage",
    image: `${C4}/fasad.jpg`,
    images: [
      `${C4}/fasad.jpg`,
      `${C4}/fasad-2.jpg`,
      `${C4}/terrasa-vid-na-more.jpg`,
      `${C4}/terrasa-vid-na-more-2.jpg`,
      `${C4}/gostinaya.jpg`,
      `${C4}/gostinaya-2.jpg`,
      `${C4}/kuhnya.jpg`,
      `${C4}/spalnya-1.jpg`,
      `${C4}/spalnya-1-krovat.jpg`,
      `${C4}/spalnya-2.jpg`,
      `${C4}/spalnya-2-zerkalo.jpg`,
      `${C4}/spalnya-deti.jpg`,
      `${C4}/spalnya-deti-2.jpg`,
      `${C4}/vannaya-1.jpg`,
      `${C4}/vannaya-2.jpg`,
      `${C4}/photo_2026-04-01_09-21-56.jpg`,
      `${C4}/photo_2026-04-01_09-22-10.jpg`,
      `${C4}/photo_2026-04-01_09-22-14.jpg`,
      `${C4}/photo_2026-04-01_09-22-17.jpg`,
      `${C4}/photo_2026-04-01_09-22-21.jpg`,
      `${C4}/photo_2026-04-01_09-22-25.jpg`,
    ],
    area: 130,
    guests: 4,
    bedrooms: 2,
    description: "Коттедж двухэтажный с панорамным видом на море. 2 спальни с санузлами, терраса, кухня с видом на море.",
    longDescription: "Коттедж №4 площадью 130 м² с панорамным видом на море. Арендуемая часть — второй и третий этажи с отдельным входом. На нижнем этаже коттеджа — открытая терраса с видом на море. Уютная гостиная с балконом. Функциональная кухня с обеденной зоной. На верхнем этаже — две просторные спальни с санузлом. Коттедж оборудован мебелью и техникой для комфортного проживания и отдыха. Есть возможность размещения двух дополнительных мест для проживания. На территории комплекса расположены: русская баня, бассейн, зона барбекю, декоративный пруд. Круглосуточная охрана с видеонаблюдением. Крытая парковка.",
    features: ["Бассейн", "Русская баня", "Вид на море", "Зона барбекю", "Wi-Fi", "Терраса"],
    price: 17000,
    price14days: 150000,
    priceMonth: 270000,
    price11months: 200000,
    href: "/cottages/kottedzh-4",
  },
];

export const apartments: Property[] = [
  {
    id: "apt-k7",
    slug: "apt-kottedzh-7",
    title: "Апартаменты в коттедже № 7",
    type: "apartment",
    image: `${A7}/apartamenty-7-v-kottedzhe-7-photo-big.jpg`,
    images: [
      `${A7}/apartamenty-7-v-kottedzhe-7-photo-big.jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big.jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(1).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(2).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(3).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(4).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(5).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(6).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(7).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(8).jpg`,
      `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(9).jpg`,
    ],
    area: 62,
    guests: 2,
    bedrooms: 1,
    description: "Комфортабельные жилые апартаменты 62 м² с видом на море.",
    longDescription: "Апартаменты площадью 62 м² на первом этаже коттеджа №7 с видом на море. Современный ремонт, тёплый пол, кондиционер. Изолированная уютная спальня, просторная кухня-гостиная, прихожая, санузел, необходимая мебель и техника. Есть возможность дополнительного размещения двух гостей. Отдельный вход с улицы. На территории комплекса: ухоженное озеленение, открытый подогреваемый бассейн, русская баня, зона барбекю, декоративный пруд, круглосуточная охрана с видеонаблюдением, крытая парковка.",
    features: ["Бассейн", "Вид на море", "Тёплый пол", "Кондиционер", "Wi-Fi", "Зона барбекю"],
    price: 5500,
    price14days: 70000,
    priceMonth: 120000,
    price11months: 65000,
    href: "/apartments/apt-kottedzh-7",
  },
  {
    id: "apt-k4",
    slug: "apt-kottedzh-4",
    title: "Апартаменты в коттедже № 4",
    type: "apartment",
    image: `${A4}/apartamenty-4-v-kottedzhe-4-photo-big.jpg`,
    images: [
      `${A4}/apartamenty-4-v-kottedzhe-4-photo-big.jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big.jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(1).jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(2).jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(4).jpg`,
      `${A4}/apartamenty-4-v-kottedzhe-4-photos-big%20(5).jpg`,
      `${A4}/photo_2026-04-08_22-40-23.jpg`,
      `${A4}/photo_2026-04-08_22-40-35.jpg`,
      `${A4}/photo_2026-04-08_22-40-38.jpg`,
      `${A4}/photo_2026-04-08_22-40-41.jpg`,
      `${A4}/photo_2026-04-08_22-40-44.jpg`,
      `${A4}/photo_2026-04-08_22-40-47.jpg`,
    ],
    area: 62,
    guests: 2,
    bedrooms: 1,
    description: "Комфортабельные жилые апартаменты 62 м² с видом на море.",
    longDescription: "Апартаменты площадью 62 м² на первом этаже коттеджа №4 с видом на море. Современный ремонт, тёплый пол, кондиционер. Изолированная уютная спальня, просторная кухня-гостиная, прихожая, санузел, необходимая мебель и техника. Есть возможность дополнительного размещения двух гостей. Отдельный вход с улицы. На территории комплекса: ухоженное озеленение, открытый подогреваемый бассейн, русская баня, зона барбекю, декоративный пруд, круглосуточная охрана с видеонаблюдением, крытая парковка.",
    features: ["Бассейн", "Вид на море", "Тёплый пол", "Кондиционер", "Wi-Fi"],
    price: 5500,
    price14days: 70000,
    priceMonth: 120000,
    price11months: 65000,
    href: "/apartments/apt-kottedzh-4",
  },
  {
    id: "apt-k5-2",
    slug: "apt-kottedzh-5-2",
    title: "Апартаменты в коттедже №5-2",
    type: "apartment",
    image: `${A52}/apartamenty-v-kottedzhe-5-2-photos-big.jpg`,
    images: [
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big.jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(1).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(2).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(3).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(5).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(6).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(7).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(8).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(9).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(10).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(11).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(14).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(15).jpg`,
      `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(17).jpg`,
    ],
    area: 64,
    guests: 2,
    bedrooms: 1,
    description: "Комфортабельные жилые апартаменты 64 м² с видом на море.",
    longDescription: "Апартаменты площадью 64 м² на первом этаже коттеджа №5 с видом на море. Современный ремонт, тёплый пол, кондиционер. Уютная спальня с джакузи, просторная кухня-гостиная, санузел, необходимая мебель и техника. Есть возможность дополнительного размещения двух гостей. Отдельный вход с улицы. На территории комплекса: ухоженное озеленение, открытый подогреваемый бассейн, русская баня, зона барбекю, декоративный пруд, круглосуточная охрана с видеонаблюдением, крытая парковка.",
    features: ["Бассейн", "Вид на море", "Джакузи", "Кондиционер", "Wi-Fi", "Зона барбекю"],
    price: 5500,
    price14days: 70000,
    priceMonth: 110000,
    price11months: 65000,
    href: "/apartments/apt-kottedzh-5-2",
  },
  {
    id: "apt-k5-1",
    slug: "apt-kottedzh-5-1",
    title: "Апартаменты в коттедже №5-1",
    type: "apartment",
    image: `${A51}/photo_2026-04-08_22-46-57.jpg`,
    images: [
      `${A51}/photo_2026-04-08_22-46-57.jpg`,
      `${A51}/photo_2026-04-08_22-47-04.jpg`,
      `${A51}/photo_2026-04-08_22-47-07.jpg`,
      `${A51}/photo_2026-04-08_22-47-09.jpg`,
      `${A51}/photo_2026-04-08_22-47-12.jpg`,
      `${A51}/photo_2026-04-08_22-47-15.jpg`,
      `${A51}/photo_2026-04-08_22-47-17.jpg`,
      `${A51}/photo_2026-04-08_22-47-19.jpg`,
      `${A51}/photo_2026-04-08_22-47-21.jpg`,
      `${A51}/photo_2026-04-08_22-47-23.jpg`,
      `${A51}/photo_2026-04-08_22-47-25.jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big.jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(1).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(2).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(18).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(19).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(20).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(22).jpg`,
      `${A51}/apartamenty-v-kottedzhe-5-1-photos-big%20(23).jpg`,
    ],
    area: 64,
    guests: 2,
    bedrooms: 1,
    description: "Комфортабельные жилые апартаменты 64 м² с видом на море.",
    longDescription: "Апартаменты площадью 64 м² на первом этаже коттеджа №5 с видом на море. Современный ремонт, тёплый пол, кондиционер. Уютная спальня с джакузи, просторная кухня-гостиная, санузел, необходимая мебель и техника. Есть возможность дополнительного размещения двух гостей. Отдельный вход с улицы. На территории комплекса: ухоженное озеленение, открытый подогреваемый бассейн, русская баня, зона барбекю, декоративный пруд, круглосуточная охрана с видеонаблюдением, крытая парковка.",
    features: ["Бассейн", "Вид на море", "Джакузи", "Кондиционер", "Wi-Fi", "Охрана"],
    price: 5500,
    price14days: 70000,
    priceMonth: 110000,
    price11months: 65000,
    href: "/apartments/apt-kottedzh-5-1",
  },
  {
    id: "apt-k2",
    slug: "apt-kottedzh-2",
    title: "Апартаменты в коттедже №2",
    type: "apartment",
    image: `${A2}/apartamenty-v-kottedzhe-2-photo-big.jpg`,
    images: [
      `${A2}/apartamenty-v-kottedzhe-2-photo-big.jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big.jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(1).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(2).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(3).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(4).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(5).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(6).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(7).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(8).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(9).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(10).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(11).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(12).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(13).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(14).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(15).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(16).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(17).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(18).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(19).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(20).jpg`,
      `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(21).jpg`,
    ],
    area: 62,
    guests: 2,
    bedrooms: 1,
    description: "Комфортабельные жилые апартаменты 62 м² с видом на море.",
    longDescription: "Апартаменты площадью 62 м² на первом этаже коттеджа №2 с видом на море. Современный ремонт, тёплый пол, кондиционер. Изолированная уютная спальня, просторная кухня-гостиная, прихожая, санузел, необходимая мебель и техника. Есть возможность дополнительного размещения двух гостей. Отдельный вход с улицы. На территории комплекса: ухоженное озеленение, открытый подогреваемый бассейн, русская баня, зона барбекю, декоративный пруд, круглосуточная охрана с видеонаблюдением, крытая парковка.",
    features: ["Бассейн", "Вид на море", "Тёплый пол", "Кондиционер", "Wi-Fi", "Зона барбекю"],
    href: "/apartments/apt-kottedzh-2",
  },
  {
    id: "apt-k3",
    slug: "apt-kottedzh-3",
    title: "Апартаменты в коттедже №3",
    type: "apartment",
    image: `${A3}/apartamenty-3-photo-big.jpg`,
    images: [
      `${A3}/apartamenty-3-photos-big.jpg`,
      `${A3}/apartamenty-3-photos-big%20(1).jpg`,
      `${A3}/apartamenty-3-photos-big%20(3).jpg`,
      `${A3}/apartamenty-3-photos-big%20(5).jpg`,
      `${A3}/apartamenty-3-photos-big%20(6).jpg`,
      `${A3}/apartamenty-3-photos-big%20(7).jpg`,
      `${A3}/apartamenty-3-photos-big%20(8).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(1).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(3).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(4).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(5).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(6).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(7).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(8).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(9).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(10).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(11).jpg`,
      `${A3}/apartamenty-3-v-kottedzhe-3-photos-big%20(12).jpg`,
    ],
    area: 60,
    guests: 2,
    bedrooms: 1,
    description: "Комфортабельные жилые апартаменты 60 м² с видом на море.",
    longDescription: "Апартаменты площадью 60 м² на первом этаже коттеджа №3 с видом на море. Современный ремонт, тёплый пол, кондиционер. Изолированная уютная спальня, просторная кухня-гостиная, прихожая, санузел, необходимая мебель и техника. Есть возможность дополнительного размещения двух гостей. Отдельный вход с улицы. На территории комплекса: ухоженное озеленение, открытый подогреваемый бассейн, русская баня, зона барбекю, декоративный пруд, круглосуточная охрана с видеонаблюдением, крытая парковка.",
    features: ["Бассейн", "Вид на море", "Кондиционер", "Wi-Fi", "Зона барбекю"],
    price: 5500,
    price14days: 70000,
    priceMonth: 120000,
    price11months: 65000,
    href: "/apartments/apt-kottedzh-3",
  },
];

export const flats: Property[] = [
  {
    id: "flat-golland-6-2",
    slug: "flat-gollandskii-6-2",
    title: "Квартира №6-2 ЖК «Голландский»",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(8).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Просторная квартира с современным ремонтом и видом на море.",
    longDescription: "Просторная квартира №6-2 в ЖК «Голландский» по ул. Звёздная 22 (совхоз Приморский, Хостинский район). Расположена на втором этаже здания с витражным остеклением и видом на море. Спальня изолированная, кухня и гостиная объединены в общее пространство. Квартира оборудована всей необходимой техникой, мебелью, посудой. Есть возможность дополнительного размещения двух гостей. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, крытая парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Охрана", "Новый ремонт"],
    price11months: 50000,
    href: "/flats/flat-gollandskii-6-2",
  },
  {
    id: "flat-golland-5",
    slug: "flat-gollandskii-5",
    title: "Квартира №5 ЖК «Голландский»",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(11).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Просторная квартира с современным ремонтом и видом на море.",
    longDescription: "Современная квартира №5-1 в ЖК «Голландский» по ул. Звёздная 22 (совхоз Приморский, Хостинский район). Расположена на первом этаже здания с витражным остеклением и видом на море. Квартира имеет общее пространство с зонированной спальней и выделенной зоной кухни-гостиной, оборудована всей необходимой техникой, мебелью, посудой. Есть возможность дополнительного размещения двух гостей. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, крытая парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Тёплый пол", "Wi-Fi", "Охрана", "Кондиционер"],
    price11months: 50000,
    href: "/flats/flat-gollandskii-5",
  },
  {
    id: "flat-zvezdnaya-8-17",
    slug: "flat-zvezdnaya-8-17",
    title: "Квартира №8 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photos-big%20(11).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 1-комн. 35 м² в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира №8 расположена на 4-ом этаже дома клубного типа, по ул. Звёздная 22-17 (Хостинский район). Панорамный вид на море. Просторная кухня-гостиная, изолированная спальня, косметический ремонт. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, крытая парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Закрытая территория"],
    price11months: 40000,
    href: "/flats/flat-zvezdnaya-8-17",
  },
  {
    id: "flat-zvezdnaya-2-17",
    slug: "flat-zvezdnaya-2-17",
    title: "Квартира №2 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photos-big%20(7).jpg`,
    ],
    area: 24,
    guests: 2,
    bedrooms: 1,
    description: "Квартира-студия 24 м² в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира-студия №2 расположена на 1-ом этаже дома клубного типа, по ул. Звёздная 22-17 (Хостинский район). Имеет общее пространство, с кухонной и спальной зонами. Вид на море. Косметический ремонт. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, крытая парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Кондиционер", "Wi-Fi", "Парковка", "Охрана", "Вид на море"],
    price11months: 35000,
    href: "/flats/flat-zvezdnaya-2-17",
  },
  {
    id: "flat-zvezdnaya-5-17",
    slug: "flat-zvezdnaya-5-17",
    title: "Квартира №5 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-19-30.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-20-16.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-20-19.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-20-22.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-20-09.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-20-25.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-20-33.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/photo_2026-04-01_09-20-36.jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photos-big%20(12).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 1-комн. 35 м² в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира 1-комн. №5 расположена на 3-ем этаже дома клубного типа, по ул. Звёздная 22-17 (Хостинский район). Панорамный вид на море. Изолированные комнаты: спальня с балконом и кухня. Прихожая зона, санузел. Косметический ремонт. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, крытая парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Балкон", "Охрана"],
    price11months: 40000,
    href: "/flats/flat-zvezdnaya-5-17",
  },
  {
    id: "flat-zvezdnaya-4-17",
    slug: "flat-zvezdnaya-4-17",
    title: "Квартира №4 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photo-big.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photo-big.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(13).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(14).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(15).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photos-big%20(16).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира-студия 35 м² с балконом в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира-студия №4 расположена на 2-ом этаже дома клубного типа, по ул. Звёздная 22-17 (Хостинский район). Имеет общее пространство, с кухонной и спальной зонами с балконом. Панорамный вид на море. Косметический ремонт. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, крытая парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Балкон"],
    price11months: 40000,
    href: "/flats/flat-zvezdnaya-4-17",
  },
  {
    id: "flat-zvezdnaya-3-17",
    slug: "flat-zvezdnaya-3-17",
    title: "Квартира №3 ул. Звёздная 22-17",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(1).jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/photo_2026-04-07_21-42-01.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/photo_2026-04-07_21-42-13.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/photo_2026-04-07_21-42-15.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/photo_2026-04-07_21-42-18.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/photo_2026-04-07_21-42-21.jpg`,
      `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/photo_2026-04-07_21-42-23.jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира-студия с балконом в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира-студия №3 расположена на 2-ом этаже дома клубного типа, по ул. Звёздная 22-17 (Хостинский район). Большая, светлая квартира. Общее пространство объединяет кухню и спальню. Просторный балкон с панорамным видом на море. Косметический ремонт. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, крытая парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Балкон"],
    price11months: 40000,
    href: "/flats/flat-zvezdnaya-3-17",
  },
  {
    id: "flat-zvezdnaya-4-16",
    slug: "flat-zvezdnaya-4-16",
    title: "Квартира №4 ул. Звёздная 22-16",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/9c910700.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/9c910700.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(13).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(14).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(15).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(16).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(17).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(18).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(19).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(20).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(21).jpg`,
      `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/kvartira-4-ul.-22-16-photos-big%20(22).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 1-комн. 35 м² в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира №4 расположена на 2-ом этаже дома клубного типа, по ул. Звёздная 22-16 (Хостинский район). Панорамный вид на море. Просторная кухня-гостиная с балконом, изолированная спальня, косметический ремонт. Собственная терраса с выходом в сад. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, подземная парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Балкон"],
    price11months: 45000,
    href: "/flats/flat-zvezdnaya-4-16",
  },
  {
    id: "flat-zvezdnaya-1-16",
    slug: "flat-zvezdnaya-1-16",
    title: "Квартира №1 ул. Звёздная 22-16",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-37-24.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-37-24.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-32.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-35.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-37.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-39.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-41.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-45.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-47.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-50.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-52.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-55.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-57.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-38-59.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-39-01.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-39-03.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-39-05.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-39-08.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-39-10.jpg`,
      `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-39-12.jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 1-комн. 35 м² в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира №1 расположена на 1 этаже дома клубного типа, по ул. Звёздная 22-16 (Хостинский район). Панорамный вид на море. Просторная кухня-гостиная с балконом, выделенная зона спальни, косметический ремонт. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, подземная парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Балкон"],
    price11months: 40000,
    href: "/flats/flat-zvezdnaya-1-16",
  },
  {
    id: "flat-zvezdnaya-2-16",
    slug: "flat-zvezdnaya-2-16",
    title: "Квартира №2 ул. Звёздная 22-16",
    type: "flat",
    image: `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/c9dfb3eb.jpg`,
    images: [
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/c9dfb3eb.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big.jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(1).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(2).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(3).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(4).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(5).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(6).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(7).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(8).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(9).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(10).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(11).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(12).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(13).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(14).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(15).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(16).jpg`,
      `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/kvartira-v-zhk-magnolija-photos-big%20(17).jpg`,
    ],
    area: 35,
    guests: 2,
    bedrooms: 1,
    description: "Квартира 1-комн. 35 м² в доме на охраняемой территории комплекса «Усадьба» с видом на море.",
    longDescription: "Квартира №2 расположена на 1-ом этаже дома клубного типа, по ул. Звёздная 22-16 (Хостинский район). Панорамный вид на море. Просторная кухня-гостиная с балконом, выделенная зона спальни, косметический ремонт. Квартира оборудована всей необходимой техникой, мебелью, посудой. На территории комплекса имеется: ухоженное озеленение, круглосуточная охрана с видеонаблюдением, подземная парковка. Возможно посещение бассейна, расположенного на территории коттеджей, по платному абонементу.",
    features: ["Вид на море", "Кондиционер", "Wi-Fi", "Парковка", "Балкон"],
    price11months: 40000,
    href: "/flats/flat-zvezdnaya-2-16",
  },
];

export const allProperties = [...cottages, ...apartments, ...flats];

export const reviews = [
  {
    id: 1,
    name: "Анна К.",
    date: "Август 2024",
    rating: 5,
    text: "Провели незабываемый отпуск! Коттедж превзошёл все ожидания — чистота, уют, потрясающий вид на море. Персонал очень внимательный и отзывчивый. Обязательно вернёмся!",
    property: "Деревянный эко коттедж №7",
  },
  {
    id: 2,
    name: "Дмитрий В.",
    date: "Июль 2024",
    rating: 5,
    text: "Отличное место для семейного отдыха. Дети были в восторге от бассейна. Расположение очень удобное — до моря 15 минут пешком.",
    property: "Коттедж №10",
  },
  {
    id: 3,
    name: "Елена и Михаил С.",
    date: "Июнь 2024",
    rating: 5,
    text: "Апартаменты выше всяких похвал! Дизайн на высшем уровне, всё продумано до мелочей. Вид с балкона — просто сказка. Спасибо за тёплый приём!",
    property: "Апартаменты в коттедже №5-2",
  },
  {
    id: 4,
    name: "Сергей Т.",
    date: "Май 2024",
    rating: 5,
    text: "Снимали Президентский коттедж на корпоратив. Всё прошло на высшем уровне — пространство идеальное, кухня полностью оснащена. Рекомендую!",
    property: "Президентский коттедж №5",
  },
  {
    id: 5,
    name: "Ирина Л.",
    date: "Сентябрь 2024",
    rating: 5,
    text: "Отдыхала с подругами, взяли апартаменты с джакузи. Очень романтичная обстановка, продуманный интерьер. Хозяева встретили с теплом. Советую всем!",
    property: "Апартаменты в коттедже №5-1",
  },
  {
    id: 6,
    name: "Алексей Н.",
    date: "Октябрь 2024",
    rating: 5,
    text: "Были с семьёй во второй раз — снова в полном восторге. Это место действительно заслуживает звания VIP. Спасибо команде за высокий уровень сервиса!",
    property: "Коттедж №1Б",
  },
];


const TC = `${BASE}/Usadba/territory/territory_cottages`;
const TT = `${BASE}/Usadba/territory/territory_teatralnaya_11`;
const TZ16 = `${BASE}/Usadba/territory/territory_zvezdnaya%2022-16%20Magnolia`;
const TZ17 = `${BASE}/Usadba/territory/territory_zvezdnaya%2022-17`;

export const galleryImages = [
  // Коттеджи
  { src: `${C7}/derevjannyi-eko-kottedzh-7-photos-big.jpg`, alt: "Деревянный эко коттедж №7", category: "Коттеджи" },
  { src: `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(1).jpg`, alt: "Эко коттедж №7", category: "Коттеджи" },
  { src: `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(5).jpg`, alt: "Эко коттедж №7 терраса", category: "Коттеджи" },
  { src: `${C10}/eko-kottedzh-10-photos-big.jpg`, alt: "Коттедж №10", category: "Коттеджи" },
  { src: `${C10}/kottedzh-10-photos-big%20(1).jpg`, alt: "Коттедж №10 интерьер", category: "Коттеджи" },
  { src: `${C5}/prezidentskii-kottedzh-5-photos-big.jpg`, alt: "Президентский коттедж №5", category: "Коттеджи" },
  { src: `${C5}/prezidentskii-kottedzh-5-photos-big%20(1).jpg`, alt: "Коттедж №5 интерьер", category: "Коттеджи" },
  { src: `${C3}/kottedzh-3-s-vidom-na-more-photos-big.jpg`, alt: "Коттедж №3 вид на море", category: "Коттеджи" },
  { src: `${C3}/kottedzh-3-photos-big%20(1).jpg`, alt: "Коттедж №3 интерьер", category: "Коттеджи" },
  { src: `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big.jpg`, alt: "Коттедж №1Б", category: "Коттеджи" },
  { src: `${C2}/kottedzh-2-s-vidom-na-more-photos-big.jpg`, alt: "Коттедж №2", category: "Коттеджи" },
  { src: `${C10}/eko-kottedzh-10-photos-big%20(1).jpg`, alt: "Коттедж №10 гостиная", category: "Коттеджи" },
  { src: `${C10}/eko-kottedzh-10-photos-big%20(2).jpg`, alt: "Коттедж №10 кухня", category: "Коттеджи" },
  { src: `${C7}/derevjannyi-eko-kottedzh-7-photos-big%20(2).jpg`, alt: "Эко коттедж №7 фасад", category: "Коттеджи" },
  { src: `${C2}/kottedzh-2-s-vidom-na-more-photos-big%20(3).jpg`, alt: "Коттедж №2 терраса с видом на море", category: "Коттеджи" },
  { src: `${C3}/kottedzh-3-s-vidom-na-more-photos-big%20(1).jpg`, alt: "Коттедж №3 фасад", category: "Коттеджи" },
  { src: `${C5}/prezidentskii-kottedzh-5-photos-big%20(2).jpg`, alt: "Коттедж №5 сад", category: "Коттеджи" },
  { src: `${C1B}/kottedzh-1b-s-vidom-na-more-photos-big%20(2).jpg`, alt: "Коттедж №1Б фасад", category: "Коттеджи" },
  { src: `${C4}/terrasa-vid-na-more.jpg`, alt: "Коттедж №4 терраса вид на море", category: "Коттеджи" },
  // Апартаменты
  { src: `${A7}/apartamenty-7-v-kottedzhe-7-photo-big.jpg`, alt: "Апартаменты в коттедже №7", category: "Апартаменты" },
  { src: `${A7}/apartamenty-7-v-kottedzhe-7-photos-big%20(1).jpg`, alt: "Апартаменты №7 гостиная", category: "Апартаменты" },
  { src: `${A4}/apartamenty-4-v-kottedzhe-4-photo-big.jpg`, alt: "Апартаменты в коттедже №4", category: "Апартаменты" },
  { src: `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(1).jpg`, alt: "Апартаменты в коттедже №5-2", category: "Апартаменты" },
  { src: `${A51}/photo_2026-04-08_22-46-57.jpg`, alt: "Апартаменты в коттедже №5-1", category: "Апартаменты" },
  { src: `${A2}/apartamenty-v-kottedzhe-2-photo-big.jpg`, alt: "Апартаменты в коттедже №2", category: "Апартаменты" },
  { src: `${A3}/apartamenty-3-photo-big.jpg`, alt: "Апартаменты в коттедже №3", category: "Апартаменты" },
  { src: `${A2}/apartamenty-v-kottedzhe-2-photos-big%20(1).jpg`, alt: "Апартаменты №2 гостиная", category: "Апартаменты" },
  { src: `${A51}/photo_2026-04-08_22-47-09.jpg`, alt: "Апартаменты №5-1 спальня", category: "Апартаменты" },
  { src: `${A52}/apartamenty-v-kottedzhe-5-2-photos-big%20(2).jpg`, alt: "Апартаменты №5-2 территория", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photo-big.jpg`, alt: "Квартира ЖК «Голландский» №6-2", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photo-big.jpg`, alt: "Квартира ЖК «Голландский» №5", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%208%20zvezdnaya%2022-17/kvartira-8-ul.-22-17-photo-big.jpg`, alt: "Квартира ул. Звёздная 22-17 №8", category: "Апартаменты" },
  { src: `${C4}/fasad.jpg`, alt: "Коттедж №4", category: "Коттеджи" },
  { src: `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-16/9c910700.jpg`, alt: "Квартира №4 ул. Звёздная 22-16", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%205%20zvezdnaya%2022-17/kvartira-5-ul.-22-17-photo-big.jpg`, alt: "Квартира №5 ул. Звёздная 22-17", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%204%20zvezdnaya%2022-17/kvartira-4-ul-zvezdnaja-22-17-photo-big.jpg`, alt: "Квартира №4 ул. Звёздная 22-17", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-17/kvartira-2-ul.-22-17-photo-big.jpg`, alt: "Квартира №2 ул. Звёздная 22-17", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%201%20zvezdnaya%2022-16/photo_2026-04-07_21-37-24.jpg`, alt: "Квартира №1 ул. Звёздная 22-16", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%202%20zvezdnaya%2022-16/c9dfb3eb.jpg`, alt: "Квартира №2 ул. Звёздная 22-16", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%205%20gollandskiy/kvartira-5-zhk-gollandskii-photos-big%20(1).jpg`, alt: "Квартира №5 ЖК «Голландский» гостиная", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(1).jpg`, alt: "Квартира №6-2 ЖК «Голландский» окна", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%206-2%20gollandkiy/kvartira-6-2-zhk-gollandskii-photos-big%20(2).jpg`, alt: "Квартира №6-2 ЖК «Голландский» кухня", category: "Апартаменты" },
  { src: `${BASE}/Usadba/flats/flat%203%20zvezdnaya%2022-17/kvartira-v-dome-17-ul.-22-photos-big%20(1).jpg`, alt: "Квартира №3 ул. Звёздная 22-17", category: "Апартаменты" },
  // Территория коттеджного комплекса
  { src: `${TC}/00c3af2c.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/0607cf06.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/0c6b8a33.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/117700bf.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/11ca9002.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/145e1b78.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/14bcb8e3.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/2b609a52.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/374a3992.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/3c45aa66.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/46c8b8fb.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/4ada4ea4.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/4fd0b0b2.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/50a7382d.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/54473f6c.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/6092a2d8.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/7593f114.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/97a7f7d9.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/98310ec8.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a6b6db7d.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a85b6e42.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a91ad334.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/a963d010.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/b2040183.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/b2ee642a.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/bc45b94a.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/c229e13f.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/c7047a07.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/c9217d58.jpg`, alt: "Территория комплекса", category: "Территория" },
  { src: `${TC}/e4a6f70b.jpg`, alt: "Территория комплекса", category: "Территория" },
  // ул. Звёздная 22-16
  { src: `${TZ16}/100579ac.jpg`, alt: "ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/2f4a48d1.jpg`, alt: "ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/4ebe94f7.jpg`, alt: "ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/705f7e35.jpg`, alt: "ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/88170944.jpg`, alt: "ул. Звёздная 22-16", category: "Территория" },
  { src: `${TZ16}/d487bc4c.jpg`, alt: "ул. Звёздная 22-16", category: "Территория" },
  // ул. Звёздная 22-17
  { src: `${TZ17}/12eb3e23.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
  { src: `${TZ17}/31061044.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
  { src: `${TZ17}/e352f0d8.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
  { src: `${TZ17}/faddbb8b.jpg`, alt: "ул. Звёздная 22-17", category: "Территория" },
];
